import Aside from "@/components/aside";
import AuthModalWrapper from "@/components/AuthModalWrapper";
import Navbar from "@/components/navbar";
import { AuthModalProvider } from "@/context/AuthModalContext";
import { BettingSlipsProvider } from "@/context/useBettingSlips";
import { MatchesProvider } from "@/context/useMatchesContext";
import QueryProvider from "@/providers/QueryProvider";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "SuperWager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <AuthModalProvider>
            <MatchesProvider>
              <BettingSlipsProvider>
                <Toaster position="top-right" richColors />
                <main className="relative">
                  <Navbar />
                  <div className="w-full min-h-screen p-[5%] flex gap-16 max-w-screen-2xl mx-auto">
                    <div className="flex-[75%]">{children}</div>
                    <Aside />
                  </div>
                  <AuthModalWrapper />
                </main>
              </BettingSlipsProvider>
            </MatchesProvider>
          </AuthModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
