import Aside from "@/components/aside";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SuperWager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        <div className="w-full min-h-screen p-[5%] flex gap-16 max-w-screen-2xl mx-auto">
          <div className="flex-[75%]">{children}</div>
          <Aside />
        </div>
      </body>
    </html>
  );
}
